import { OpenAPIGenerator } from "@orpc/openapi";
import { appRouter } from "./routers";
import * as fs from "fs";
import * as path from "path";
import { ZodToJsonSchemaConverter } from "@orpc/zod/zod4";

// 因為要用 await，所以要包一個立即執行的 async function
(async () => {
  try {
    const generator = new OpenAPIGenerator({
      schemaConverters: [new ZodToJsonSchemaConverter()],
    });

    // 🔥 關鍵修正：加上 await
    const doc = await generator.generate(appRouter, {
      info: {
        title: "My Project API",
        version: "1.0.0",
        description: "Generated by @orpc/openapi",
      },
      servers: [
        {
          url: "http://localhost:3000/api",
          description: "Local Development",
        },
      ],
    });

    const outputPath = path.join(process.cwd(), "public", "openapi.json");
    fs.writeFileSync(outputPath, JSON.stringify(doc, null, 2));

    console.log("✅ OpenAPI Document Generated Successfully!");
  } catch (error) {
    console.error("❌ Generation failed:", error);
  }
})();
