import { OpenAPIGenerator } from '@orpc/openapi';
import { appRouter } from './routers'; // 你的 oRPC Router
import * as fs from 'fs';
import * as path from 'path';

// 1. 初始化產生器 (這裡保持留白，不需要參數)
const generator = new OpenAPIGenerator();

// 2. 呼叫 generate 時才傳入 (1) Router 和 (2) Info 設定
const doc = generator.generate(appRouter, {
  info: {
    title: 'My Project API',
    version: '1.0.0',
    description: 'Generated by @orpc/openapi',
  },
  servers: [
    {
      url: 'http://localhost:3000/api',
      description: 'Local Development',
    },
  ],
});

const outputPath = path.join(process.cwd(), 'openapi.json');
fs.writeFileSync(outputPath, JSON.stringify(doc, null, 2));

console.log('✅ OpenAPI Document Generated Successfully!');